[project]
name = "my_project"
version = "0.1.0"
description = "My Python Project"
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true 